name: build

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push - ubuntu/21.04
        uses: docker/build-push-action@v2
        with:
          context: ubuntu/21.04
          push: true
          tags: thystips/molecule-systemd:ubuntu-21.04
      -
        name: Build and push - ubuntu/20.04
        uses: docker/build-push-action@v2
        with:
          context: ubuntu/20.04
          push: true
          tags: thystips/molecule-systemd:ubuntu-20.04
      -
        name: Build and push - debian/11
        uses: docker/build-push-action@v2
        with:
          context: debian/11
          push: true
          tags: thystips/molecule-systemd:debian-11
      -
        name: Build and push - debian/10
        uses: docker/build-push-action@v2
        with:
          context: debian/10
          push: true
          tags: thystips/molecule-systemd:debian-10
      -
        name: Build and push - centos-7
        uses: docker/build-push-action@v2
        with:
          context: centos/7
          push: true
          tags: thystips/molecule-systemd:centos-7
